name: 'setup-python'
description: 'setup Python environment'
runs:
  using: "composite"
  steps:
    - name: checkout-repo
      uses: actions/checkout@v3
    - name: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: install-poetry
      run: python -m pip install poetry
    - name: install-deps
      run: poetry install
    - name: run-mypy
